using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TrinityCore_Manager.Database.Enums.Item_Enums
{
    public enum ItemStatType
    {

        	MANAPOWER = 0,
			HEALTH = 1,
			AGILITY = 3,
			STRENGTH = 4,
			INTELLECT = 5,
			SPIRIT = 6,
			STAMINA = 7,
			DEFENSE_SKILL_RATING = 12,
			DODGE_RATING = 13,
			PARRY_RATING = 14,
			BLOCK_RATING = 15,
			MELEE_HIT_RATING = 16,
			RANGED_HIT_RATING = 17,
			SPELL_HIT_RATING = 18,
			CRIT_MELEE_RATING = 19,
			CRIT_RANGED_RATING = 20,
			CRIT_SPELL_RATING = 21,
			HIT_TAKEN_MELEE_RATING = 22,
			HIT_TAKEN_RANGED_RATING = 23,
			HIT_TAKEN_SPELL_RATING = 24,
			CRIT_TAKEN_MELEE_RATING = 25,
			CRIT_TAKEN_RANGED_RATING = 26,
			CRIT_TAKEN_SPELL_RATING = 27,
			HASTE_MELEE_RATING = 28,
			HASTE_RANGED_RATING = 29,
			HASTE_SPELL_RATING = 30,
			HIT_RATING = 31,
			CRIT_RATING = 32,
			HIT_TAKEN_RATING = 33,
			CRIT_TAKEN_RATING = 34,
			RESILIENCE_RATING = 35,
			HASTE_RATING = 36,
			EXPERTISE_RATING = 37,
			ATTACK_POWER = 38,
			RANGED_ATTACK_POWER = 39,
			FERAL_ATTACK_POWER_NOT_USED_AS_OF_V_3_3 = 40,
			SPELL_HEALING_DONE = 41,
			SPELL_DAMAGE_DONE = 42,
			MANA_REGENERATION = 43,
			ARMOR_PENETRATION_RATING = 44,
			SPELL_POWER = 45,
			HEALTH_REGEN = 46,
			SPELL_PENETRATION = 47,
			BLOCK_VALUE = 48

    }
}
